# Generated by Django 2.2.4 on 2019-08-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_handbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handbook',
            options={'verbose_name': 'Phone HandBook'},
        ),
    ]
